scan_planner_node:
  ros__parameters:
    use_sim_time: false

    fsm.navi_mode: 3      #导航模式
    fsm.thresh_replan: 1.0    #重规划阈值，距离局部终点多远时开启下一次规划
    fsm.thresh_no_replan: 0.1   #离目标点距离小于该阈值时不再重规划 
    fsm.planning_horizon: 3.5   #局部规划范围
    fsm.emergency_time: 1.0     #碰撞还有多久发生时急停，大于这个数先尝试重规划，否则急停
    fsm.fail_safe: true         #是否允许急停保护
    fsm.max_replan_fail_count: 1000   #连续规划失败多少次后进入停车
    fsm.point_global_dist: 0.4  #全局规划取点间隔 

    grid_map.resolution: 0.1 #0.05   # 地图分辨率   0.1
    grid_map.sliding_map_size_x: 10.0 #滑动地图大小
    grid_map.sliding_map_size_y: 10.0
    grid_map.sliding_map_size_z: 5.0
    grid_map.local_update_range_x: 10.0 #7.0  # 局部地图更新范围
    grid_map.local_update_range_y: 10.0 #7.0
    grid_map.local_update_range_z: 3.0 #2.5
    grid_map.map_sliding_en: true   #是否启用滑动地图
    grid_map.map_sliding_thresh: 0.2   #机器人移动多少距离后地图滑动
    grid_map.double_cylinder_radius: 0.3 #0.35   #障碍物膨胀半径                                     0.5
    grid_map.double_cylinder_offset: 0.3 #0.35 #0.18    #两个圆柱体中心距离                              参考：0.35
    grid_map.body_height: 0.5 #0.4               #机器人身体高度
    grid_map.obstacles_inflation_z_up: 0.3 #0.4    #机器人上方碰撞膨胀                            参考：0.4
    grid_map.obstacles_inflation_z_down: 0.15 #0.1 #机器人下方碰撞膨胀    111   0.4                参考：0.2
    grid_map.frame_id: map      #地图坐标系
    grid_map.sliding_map_frame_id: sliding_map  #滑动地图tf名字
    grid_map.ground_height: -0.1   #-0.0   #地面高度   -0.2
    grid_map.sensor_type: lidar   #传感器类型，lidar或depth_camera
    grid_map.cloud_is_world: true #点云是否在世界坐标系下
    grid_map.need_extrinsic: false  #是否需要外部参数

    grid_map.cx: 321.04638671875  #相机内参
    grid_map.cy: 243.44969177246094
    grid_map.fx: 387.229248046875
    grid_map.fy: 387.229248046875
    grid_map.depth_filter_maxdist: 3.0
    grid_map.depth_filter_mindist: 0.3
    grid_map.depth_filter_margin: 1
    grid_map.k_depth_scaling_factor: 1000.0
    grid_map.skip_pixel: 2

    grid_map.p_hit: 0.85    # 激光扫到障碍物时，占据概率增加多少，使用贝叶斯更新公式计算占据概率（L=log(P/1-P)）
    grid_map.p_miss: 0.30   # 激光未扫到障碍物时，占据概率减少多少
    grid_map.p_min: 0.12    # 占据概率最小值
    grid_map.p_max: 0.98    # 占据概率最大值
    grid_map.p_occ: 0.80    # 占据概率阈值，大于该值认为是障碍物
    grid_map.max_ray_length: 5.0    # 激光最大射线长度，超过该长度的激光不参与更新地图
    grid_map.vis_height: 0.3      #灰度图显示高度
    grid_map.show_occ_time: false   #是否显示Occupancy更新时间

    manager.max_vel: 0.5 #0.75   #最大速度
    manager.max_acc: 0.3 #0.5    #最大加速度
    manager.max_jerk: 2.0 #4.0   #最大加加速度
    manager.control_points_distance: 0.2 #0.2  #控制点之间的期望距离：B样条控制点间距，越小轨迹越细，计算量越大
    manager.feasibility_tolerance: 0.5  #轨迹容差，越小越严格
    manager.planning_horizon: 3.5 #7.5       #局部规划范围

    optimization.lambda_smooth: 1.1 #1.0   #平滑权重   轨迹不够平滑时增大
    optimization.lambda_collision: 7.0 #1.0  #避障权重，越大就离障碍物越远
    optimization.lambda_feasibility: 0.1  #动力学约束权重   速度、加速度超限时增大
    optimization.lambda_fitness: 1.2   #1.2 #1.0    #拟合初始轨迹权重  轨迹偏离参考路径太多时增大
    optimization.dist0: 0.45 #0.6  #0.2   # 安全距离  台阶纵升：0.3
    optimization.max_vel: 0.5 #0.75
    optimization.vel_tolerance: 1.0   # 速度容差
    optimization.max_acc: 0.3 #0.5
    optimization.acc_tolerance: 1.0   # 加速度容差
    optimization.order: 3   #3阶B样条
